spring:
  datasource:
    url: jdbc:mysql://localhost:3306/people_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB
#  sql:
#    init:
#      mode: always

executor:
  core-pool-size: 2
  max-pool-size: 4

csv:
  validator:
    student-field-count: 10
    employee-field-count: 10
    pensioner-field-count: 9
    max-allowed-errors: 100