spring:
  datasource:
    url: jdbc:mysql://localhost:3306/people_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB

executor:
  core-pool-size: 2
  max-pool-size: 4

upload:
  batch-size: 5000